---
deployment:
  tasks:
    
    pre_deploy:
    # Install PHP dependencies
    - composer install --no-dev --prefer-dist --optimize-autoloader
    # Clear stale caches
    - php artisan clear-compiled
    - php artisan config:clear
    - php artisan route:clear
    - php artisan view:clear
    # Run database migrations
    - '[ -f artisan ] && php artisan migrate --force'
    # Cache for performance
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
    # Link storage
    - '[ -d storage ] && php artisan storage:link'
  post_deploy:
    - '[ -f artisan ] && php artisan storage:link'
